apiVersion: apps/v1
kind: Deployment
metadata:
  name: utcdate-service
  labels:
    app: utcdate-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: utcdate-service
  template:
    metadata:
      labels:
        app: utcdate-service
    spec:
      containers:
      - name: utcdate
        image: buzor/utcdate:1.3
        ports:
        - containerPort: 3001
##      - containerPort: 3001
